### ISSUE TITLE
Error on windows 7 builds

### ISSUE THREAD

**Issue by ryancinsight** [SchrodingerZhu/snmalloc-rs#135]
Placing this here since I'm not sure if it's on rust side,

Using snmalloc causes windows 7 waitforsingleobject error despite working on windows 10 normally
![image](https://user-images.githubusercontent.com/55164720/116283572-e106d900-a740-11eb-868a-99d79e42d2f9.png)

Mimalloc does not cause the same issue though.

@mjp41 any ideas where this error could be coming from, I tried injecting dll's and reinstalling vc_redist but windows 7 gave me same error despite windows 10 being fine with it.

**Comment by mjp41** [comment]
That is strange it is not something I have tested.  I don't have a Windows 7 machine to run on.  

There are very few dependencies on the underlying platform.  Did you compile on a Windows 7 machine?  Or move the binary too it? 

Which version of snmalloc-rs is it, or which snmalloc commit?

My main guess would be the code 
https://github.com/microsoft/snmalloc/blob/017d4b1a599f19c4ac1424cb3a2c56ffe610c597/src/pal/pal_windows.h#L82-L108

Removing `LowMemoryNotification` from the PalFeatures and commenting out all the code mentioning low memory notification in `pal_windows.h` could rule that out.

Otherwise, not sure where we call `WaitForSingleObject` as we avoid any dependency on platform locking and signals.

**Comment by ryancinsight** [comment]
The snmalloc-Rs is 0.2.26 and the snmalloc commit should be 1d12e34.

I am compiling on windows 10 and transferring to other peoples windows 7 but I have no errors on their laptops using the system allocator or the rust mimalloc crate so I am getting the impression it's in snmalloc or snmalloc-rs. 

I do have a windows 7 laptop somewhere around here so I'll try to find that and see if I can compile on there and work properly.

**Comment by mjp41** [comment]
Okay, so there is the following bit of code:
```C++
#  ifdef NTDDI_WIN10_RS5
#    if (NTDDI_VERSION >= NTDDI_WIN10_RS5) && \
      (WINVER >= _WIN32_WINNT_WIN10) && !defined(USE_SYSTEMATIC_TESTING)
#      define PLATFORM_HAS_VIRTUALALLOC2
#    endif
#  endif
```
Which is detecting the target.  If you can compile with the `define` commented out, then it won't try to use `VirtualAlloc2`, which is only supported on Win10.

**Comment by SchrodingerZhu** [comment]
Snmalloc-rs explicitly requires mincore as a library dependency. Does it matter here?

**Comment by mjp41** [comment]
So in the CMake there is an option:
```CMake
if (WIN32)
  set(WIN8COMPAT FALSE CACHE BOOL "Avoid Windows 10 APIs")
  if (WIN8COMPAT)
    target_compile_definitions(snmalloc_lib INTERFACE -DWINVER=0x0603)
    message(STATUS "snmalloc: Avoiding Windows 10 APIs")
  else()
    message(STATUS "snmalloc: Using Windows 10 APIs")
    # VirtualAlloc2 is exposed by mincore.lib, not Kernel32.lib (as the
    # documentation says)
    target_link_libraries(snmalloc_lib INTERFACE mincore)
  endif()
endif()
```
So I think this can be set with 
```
-DWIN8COMPAT=On
```
Not sure if this is exposed through to Rust.

**Comment by SchrodingerZhu** [comment]
no. seems that I havent exposed any feature flag for that.

**Comment by ryancinsight** [comment]
Ok, I can confirm that the issue is win8compat feature, I will submit pull request for addition shortly
